# Generated by Django 3.1 on 2020-08-07 04:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 4, 46, 55, 773123, tzinfo=utc)),
        ),
    ]
